name: Bug report
description: File a bug/defect report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened, and what did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Provide steps, code, or links to reproduce the issue.
      placeholder: 1) Go to..., 2) Click..., 3) See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versions / environment
      description: Commit SHA, Node.js version, OS, browser (if GUI), etc.
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs or screenshots.
      render: shell


